language: objective-c

before_install:
  - gem install cocoapods -v '0.32.1'        

script:
  - xcodebuild -workspace GreatReader.xcworkspace -scheme GreatReader -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=7.1' test